# Generated by Django 4.0.4 on 2022-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
