# Generated by Django 4.0.4 on 2022-04-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='descriptions',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_open',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='review_count',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='zipcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
