# Generated by Django 4.0.3 on 2022-11-01 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=20)),
                ('time_required', models.CharField(max_length=20)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='quickfeedApp.category')),
            ],
        ),
    ]
