# Generated by Django 4.0.3 on 2022-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0002_business_image1_user_city_user_state_user_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
