# Generated by Django 4.0.3 on 2022-11-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0003_business_category_id_business_price_business_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='business',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='business',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='business',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='business',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
