# Generated by Django 4.0.3 on 2022-12-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0004_business_image2_business_image3_business_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='ratings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
            preserve_default=False,
        ),
    ]
