# Generated by Django 4.0.3 on 2022-12-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0005_reviews_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_id',
        ),
    ]
