# Generated by Django 4.0.3 on 2022-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0006_remove_reviews_business_id_remove_reviews_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
