# Generated by Django 4.0.3 on 2022-12-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0007_alter_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='quickfeedApp.business'),
        ),
    ]
