# Generated by Django 4.0.3 on 2022-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfeedApp', '0009_reviews_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
